# Generated by Django 4.1.7 on 2023-05-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_user_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
